version: '3.8'
services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server
    environment:
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
    ports:
      - "6379:6379"
